import argparse     
       
parser = argparse.ArgumentParser()
parser.add_argument('--seed', type=int, default = 1)
parser.add_argument('--dataset', type=str, default='WikiCS')
parser.add_argument('--gpu_num', type=str, default='cuda:0')
parser.add_argument('--linear', type=bool, default=False)
parser.add_argument('--embedding_train', type=bool, default = True)
parser.add_argument('--teacher_eval', type=bool, default = False)

parser.add_argument('--node_p', type=float, default=0.7)
parser.add_argument('--edge_p', type=float, default=0.7)
parser.add_argument('--epoch', type=int, default=10000)
parser.add_argument('--lrdec_1', type=float, default=0.8)
parser.add_argument('--lrdec_2', type=int, default=200)
parser.add_argument('--lr', type=float, default=0.01)
parser.add_argument('--dropout', type=float, default=0.6)
parser.add_argument('--test', type=int, default=10000)
parser.add_argument('--tau', type=float, default=0.7)
parser.add_argument('--hidden_num', type=int, default = 64)
parser.add_argument('--head', type=int, default = 4)
parser.add_argument('--out_channels', type=int, default = 512)
parser.add_argument('--write', type=int, default = 0)
parser.add_argument('--ratio', type=float, default=0.3)
parser.add_argument('--batch_size', type=int, default=128)
parser.add_argument('--patience', type=int, default = 200)

parser.add_argument('--embedding_dim', type=int, default = 64)
parser.add_argument('--walk_length', type=int, default = 5)
parser.add_argument('--context_size', type=int, default = 5)
parser.add_argument('--walks_per_node', type=int, default = 5)
parser.add_argument('--node2vec_batchsize', type=int, default = 512)
parser.add_argument('--node2vec_epoch', type=int, default = 100)
parser.add_argument('--node2vec_lr', type=float, default = 0.01)
parser.add_argument('--node2vec_neg_samples', type=int, default = 5)
parser.add_argument('--p', type=float, default = 1.0)
parser.add_argument('--q', type=float, default = 1.0)

parser.add_argument('--l1_e', type=int, default = 4)
parser.add_argument('--l2_e', type=int, default = 1)
parser.add_argument('--l12_e', type=int, default = 1)
parser.add_argument('--l1_f', type=int, default = 1)
parser.add_argument('--l2_f', type=int, default = 4)
parser.add_argument('--l12_f', type=int, default = 1)
parser.add_argument('--l1_b', type=int, default = 2)
parser.add_argument('--l2_b', type=int, default = 2)
parser.add_argument('--l12_b', type=int, default = -1)

    
args = parser.parse_args()